# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de842e812ff03da23c393059adbf2ef810d3fb969dd7758766cbb143892052dd4a2208ff7338da971bc5d885c4322673d1569e1422ef06e08540396c43f2fad7

test:
  secret_key_base: ea68fd5c42d109673ad115ab333222ec6e959a1ee62edfcdc3a67fbe5ca65abf986cb94d194972e7a81e2c8b709df4ae03c2689fe3ef8d7cf39fbdbc5b4f9711

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
